baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "ALDental | Profesionales de la sonrisa "
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Inicio"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Sobre Nosotros"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Servicios"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contactanos"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "ALDental | Profesionales de la sonrisa "
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contactanos"
    url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.png"
    heading               = "ALDental | Profesionales de la sonrisa"
    tagline               = "TRABAJAMOS PARA VERTE SONREIR"
    primary_button        = "Especialidades"
    primary_button_url    = "portfolio"
    secondary_button      = "Contactanos"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Nuestras Especialidades"
    subtitle  = "Nos esforzamos para que puedas sonreir con confianza."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "DEJANOS ASESORARTE"
    primary_button      = "Contactanos"
    primary_button_url  = "contact"
    secondary_button    = "Videos y Procedimientos"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Visitanos"
      address = "Cristóbal Colón y o Av. H 1032, Zona Centro, 22000 Tijuana, B.C."
      phone   = "409-896-1444"
      email   = "contact@aldental.mx"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Sobre Nosotros"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Servicios"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contactanos"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
        [[params.footer.social.link]]
          name = "Youtube"
          url  = "#"
        [[params.footer.social.link]]
          name = "Pinterest"
          url  = "#"
        # [[params.footer.social.link]]
        #   name = "Instagram"
        #   url  = "#"
      # # Footer Service
      # [params.footer.service]
      #   title       = "We help brands:"
      #   description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
